# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a47e408eade3693b4c3a33bab5cd42338e0a23f766767b0619540e07a8da0d5d7e3d28a82fc133296877a3e6aec488af7524084f8744171a2826ad04ff88d849

test:
  secret_key_base: d22443cbc5ceeae643bdbc57ae1fe9a62fcfdeb6ceca641102d02d3a01ec81dd7deea64c2068d1df3d999a88667f0eb6e90e0eb7e405ceafedc08aa6e709b48c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
